export const recipes = [
  {
    recipe_title: 'bolognese',
    tags: ['pasta', 'gluten', 'meat'],
    ingredients: [
      'spaghetti',
      'chopped meat',
      'onion',
      'carrot',
      'celery',
      'tomato',
      'tomato sauce',
      'salt',
      'black paper',
      'white paper',
      'parmesan',
    ],
    preparing: ['boil', 'slice', 'stew'],
  },
  {
    recipe_title: 'alfredo',
    tags: ['pasta', 'gluten', , 'Vegetarian'],
    ingredients: ['fettucini', 'cream', 'parmesan', 'salt', 'white paper'],
    preparing: ['boil', 'slice', 'stew'],
  },
  {
    recipe_title: 'carbonara',
    tags: ['pasta', 'gluten', 'eggs', 'meat'],
    ingredients: [
      'spaghetti',
      'bacon',
      'egg',
      'parmesan',
      'black paper',
      'salt',
    ],
    preparing: ['boil', 'slice', 'fry'],
  },
  {
    recipe_title: 'margarita',
    tags: ['pizza', , 'gluten', 'Vegetarian'],
    ingredients: [
      'pizza dough ',
      'tomato sauce',
      'mozzarella',
      'basil',
      'olive oil',
      'salt',
      'black paper',
    ],
    preparing: ['roll out dough', 'slice', 'bake'],
  },
  {
    recipe_title: 'peperoni',
    tags: ['pizza', 'gluten', 'Vegetarian'],
    ingredients: [
      'pizza dough',
      'tomato sauce',
      'mozzarella',
      'peperoni',
      'olive oil',
      'oregano',
      'black paper',
    ],
    preparing: ['roll out dough', 'slice', 'bake'],
  },
  {
    recipe_title: 'capricciosa',
    tags: ['pizza', 'gluten', 'meat'],
    ingredients: [
      'pizza dough',
      'tomato sauce',
      'mozzarella',
      'ham',
      'mushroom',
      'artichoke',
      'oregano',
      'salt',
      'black paper',
      'olives',
    ],
    preparing: ['roll out dough', 'slice', 'bake'],
  },
];
